config/routes.rb
Rails.application.routes.draw do
  get 'expenses/index'

  get 'statistics/index'
  post '/import_statistics'=> 'statistics#import_statistics'
  post '/import_expenses'=> 'expenses#import_expenses'
  get '/esearch'=> 'expenses#esearch'
  get '/gendersearch'=> 'statistics#gendersearch'
  get '/statdownload' => 'statistics#statdownload'
  devise_for :users

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  require 'open-uri'
  require 'csv'

  def self.import_data
    url="https://catalogue.data.gov.bc.ca/dataset/a16d7095-9577-4c81-a800-33763ed75c8e/resource/b8fea73b-cb28-43aa-ab22-ce52e80f9941/download/bchealthservicesbygenderandhealthservicedeliveryarea.csv"
    
    csv = open(url)
    CSV.new(csv).each_with_index  do |row, i|      
      next if i == 0
      Expense.create!(hsda:row[0], ha:row[1], service:row[2], service_type:row[3],
                        m_20052006:row[4], m_20062007:row[5], m_20072008:row[6], m_20082009:row[7],
                        m_20092010:row[8], f_20052006:row[9], f_20062007:row[10], f_20072008:row[11],
                        f_20082009:row[12], f_20092010:row[13])
      next if i==10 && Rail.env=="test"
    end    
  end 
end

app/models/statistic.rb
class Statistic < ApplicationRecord
  
  require 'open-uri'
  require 'csv'

  def self.import_data
    url="https://catalogue.data.gov.bc.ca/dataset/ecc0b2fe-1287-46fd-8fc1-29dad621c0ce/resource/1665c496-7e16-487a-bb6a-54f05d166bc7/download/2016_census_profiles_by_health_region.csv"
    
    csv = open(url)
    CSV.new(csv).each_with_index  do |row, i|      
      next if i == 0
      Statistic.create(dimension:row[0], british_columbia:row[1], ha_total:row[2], ha1_interior:row[3],
                        ha2_fraser:row[4], ha3_vancouver_coastal:row[5], ha4_vancouver_island:row[6], ha5_northern:row[7])
      next if i==10 && Rail.env=="test"
    end    
  end  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @data = Expense.page(params[:page]).per(50)
  end

  def import_expenses
    begin      
      @data = Expense.import_data
      redirect_to expenses_index_path,notice: "Imported successfully"
    rescue  
      redirect_to expenses_index_path,notice: "Unsuccessful"
    end    
  end

  def esearch    
    if params[:stype].present?
      @stypes = Expense.where(service_type:params[:stype])
    else
      @services = Expense.where(service:params[:service])
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    @data = Statistic.page(params[:page]).per(50)
  end

  def import_statistics
    begin      
      @data = Statistic.import_data
      redirect_to statistics_index_path,notice: "Imported successfully"
    rescue
      redirect_to statistics_index_path,notice: "Unsuccessful"
    end    
  end

  def gendersearch
    @stat = get_details(params[:gender])
  end

  def get_details(val)
		sql="SELECT	dimension, SUM (british_columbia) AS SUM_of_British_Columbia ,SUM (ha_total) AS SUM_of_HA_Total,
        SUM (ha1_interior) AS SUM_of_HA1_Interior,SUM (ha2_fraser) AS SUM_of_HA2_Fraser,
        SUM (ha3_vancouver_coastal) AS SUM_of_HA3_Vancouver_Coastal,SUM (ha4_vancouver_island) AS SUM_of_HA4_Vancouver_Island,
        SUM (ha5_northern) AS SUM_of_HA5_Northern
        FROM statistics WHERE dimension LIKE '%#{val}%' GROUP BY dimension;"   
    ActiveRecord::Base.connection.exec_query(sql)
  end
  
  def statdownload
    val=eval(params[:tab])[:value] 
    begin
      @results = get_details(val).to_a
      package = Axlsx::Package.new
      package.workbook do|wb|
        styles = wb.styles
        wb.add_worksheet(name: "Report") do |sheet|
          sheet.add_row ["Dimension" ,"British Columbia" , "HA Total" , 
          "HA1 Interior","HA2 Fraser","HA3 Vancouver Coastal","HA4 Iancouver Island","HA5 Northern"]
          @results.each do |result|
            sheet.add_row [ result["dimension"] , result["sum_of_british_columbia"] , result["sum_of_ha_total"] , 
            result["sum_of_ha1_interior"] , result["sum_of_ha2_fraser"] , 
            result["sum_of_ha3_vancouver_coastal"] ,result["sum_of_ha4_vancouver_island"],result["sum_of_ha5_northern"] ]			          
	        end 
			  end
      end    
      package.use_shared_strings = true
      report =  Date.today.strftime("%B") + "_"  + "stat_report"
      package.serialize(Rails.root.join('public/report/', report + '.xlsx'))
	    send_file("#{Rails.root.join('public/report/', report + '.xlsx')}", :type => 'application/excel')
    rescue
      render :json=> { :status=> false }
    end
	end  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_service_list
		service = {
			'Medical'=>'Medical',
			'Other Health Practitioners'=>'Other Health Practitioners'
		}
  end
  
  def get_service_type_list
		service_type = {
			'Expenditures'=>'Expenditures',
      'Patient Count'=>'Patient Count',
      'Services'=>'Services'
		}
	end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
  def gender_list
		gender = {
			'Male'=>'Male',
      'Female'=>'Female'
		}
	end  
end

app/views/expenses/_service_expenses.html.erb
<table id="datatbl",class="table table-hover">
<thead>
  <tr>
    <th>HSDA </th>
    <th>HA </th>
    <th>Service </th>
    <th>Service Type </th>
    <th>M_20092010 </th>
    <th>F_20092010</th>
  </tr>
</thead>
<tbody>
  <%  @services.each do |data| %>
    <tr>
      <td><%= data.hsda %></td>
      <td><%= data.ha %></td>
      <td><%= data.service %></td>
      <td><%= data.service_type %></td>
      <td><%= data.m_20092010 %></td>
      <td><%= data.f_20092010 %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/expenses/_stype_expenses.html.erb
<table id="datatbl",class="table table-hover">
<thead>
  <tr>
    <th>HSDA </th>
    <th>HA </th>
    <th>Service </th>
    <th>Service Type </th>
    <th>M_20092010 </th>
    <th>F_20092010</th>
  </tr>
</thead>
<tbody>
  <%  @stypes.each do |data| %>
    <tr>
      <td><%= data.hsda %></td>
      <td><%= data.ha %></td>
      <td><%= data.service %></td>
      <td><%= data.service_type %></td>
      <td><%= data.m_20092010 %></td>
      <td><%= data.f_20092010 %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/expenses/esearch.js.erb
$('.js_service_type').empty();
$(".st_index").remove();
<% if params[:stype].present?%>  
  $('.js_service_type').append("<%= escape_javascript( render partial: 'stype_expenses', locals: { stypes: @stypes }) %>");
<% else%>
  $('.js_service_type').append("<%= escape_javascript( render partial: 'service_expenses', locals: { stypes: @services}) %>");
<%end%> 

app/views/expenses/index.html.erb
<div align="center">
  <h1>Expenses</h1>
  <div> 
    <%= button_to 'Import Expenses', import_expenses_path, method: 'post',class: "st_import_data"  %>
  </div>
  <%if @data.empty?%>
    <h4>Data not available</h4> 
  <%else%>  
    <div class="row">
      
      <%= paginate @data %>
      <div class="st_filter">
        <%= form_with url: esearch_path do |f| %>
          <%= f.label :service %>
          
          <%= select_tag("service", options_for_select(get_service_list,params[:per_page].to_i),
          {:name => "service",:include_blank => 'Select Service',:onchange=>"getservices(this);"} ) %>
          <%= f.label :service_type %>
          <%= select_tag("service_type", options_for_select(get_service_type_list,params[:per_page].to_i),
          {:name => "service_type",:include_blank => 'Select Service Type',:onchange=>"getservicetypes(this);"} ) %>
          
        <% end %>
      </div>
    </div>
    <div class="js_service_type">
    </div>
    
    <div class="st_index">
      <div class="box-body">
        <table id="datatbl",class="table table-hover">
          <thead>
            <tr>
              <th>HSDA </th>
              <th>HA </th>
              <th>Service </th>
              <th>Service Type </th>
              <th>M_20092010 </th>
              <th>F_20092010</th>
            </tr>
          </thead>
          <tbody>
            <%  @data.each do |data| %>
              <tr>
                <td><%= data.hsda %></td>
                <td><%= data.ha %></td>
                <td><%= data.service %></td>
                <td><%= data.service_type %></td>
                <td><%= data.m_20092010 %></td>
                <td><%= data.f_20092010 %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <%end%>
  
</div>

app/views/home/index.html.erb
<div align="center">
  <h1>Welcome to CensusPortal</h1>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <a href="#default" class="logo">CensusPortal</a>
  <div class="header-right">
    <p> Welcome <%= current_user.username%>
    <%= link_to('Logout'.html_safe, destroy_user_session_path, method: :delete,class:"active")  %>    
  </div>
</div>
<%if current_user.is_admin==true%>
  <div id="mySidebar" class="sidebar">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <%= link_to 'Statistics', statistics_index_path ,class:"stat_cls" %><br/>
    <%= link_to 'Expenditure', expenses_index_path ,class:"expense_cls"%><br/>
  </div>    
  <div id="main">
    <button class="openbtn" onclick="openNav()">&#9776; Open Sidebar</button>         
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sensus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if user_signed_in?%>
      <%= render :partial => "layouts/header" %>    
    <%end%>
    <div class="col-md-12">
      <% flash.each do |key, message| %>
        <div class="text-center alert alert-<%= key == 'notice'? 'success': 'danger' %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <script>
    function openNav() {
      document.getElementById("mySidebar").style.width = "250px";
      document.getElementById("main").style.marginLeft = "250px";
    }
    
    /* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
    function closeNav() {
      document.getElementById("mySidebar").style.width = "0";
      document.getElementById("main").style.marginLeft = "0";
    }
    </script>
  </body>
</html>

app/views/statistics/_stat_data.html.erb
<%= form_tag(statdownload_path(@stat), {:method => :get}) do %>
	<h3 style="margin:1%;"></h3>

	<div class="box box-info">
	  <div class="box-body">
		  <div class="row">
		  	<div class="col-md-12">
          <div class="text-center">
          <%= hidden_field_tag :tab ,value: params[:gender] %>
            <%= submit_tag "Download",format: :xls, class: "btn d_btn btn-success" %>	
            
		  			<%#= link_to   'Print', { :action => "get_lms_final_report", :controller => "user_answers",format: :xls}, :class=> "btn btn-primary",target: '_blank'%>
		  		</div>
		  	</div>
		  </div>
    </div>
  </div>

<% end %>
<table id="datatbl",class="table table-hover">
<thead>
  <tr>
    <th>Dimension </th>
    <th>British Columbia </th>
    <th>HA Total </th>
    <th>HA1 Interior </th>
    <th>HA2 Fraser </th>
    <th>Vancouver Coastal </th>
    <th>HA4 Vancouver Island </th>
    <th>HA5 Northern </th>
  </tr>
</thead>
<tbody>
  <%  @stat.each do |data| %>
    <tr>
      <td><%= data["dimension"] %></td>
      <td><%= data["sum_of_british_columbia"] %></td>
      <td><%= data["sum_of_ha_total"] %></td>
      <td><%= data["sum_of_ha1_interior"] %></td>
      <td><%= data["sum_of_ha2_fraser"] %></td>
      <td><%= data["sum_of_ha3_vancouver_coastal"] %></td>
      <td><%= data["sum_of_ha4_vancouver_island"]%></td>
      <td><%= data["sum_of_ha5_northern"] %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/statistics/gendersearch.js.erb
$('.js_gender').empty();
$(".st_index").remove();
<% if params[:gender].present?%>  
  $('.js_gender').append("<%= escape_javascript( render partial: 'stat_data', locals: { stat: @stat }) %>");
<%end%>

app/views/statistics/index.html.erb
<div align="center">
  <h1>Statistics</h1>
  <div> 
    <%= button_to 'Import Statistics', import_statistics_path, method: 'post',class: "st_import_data"  %>
  </div>
  <%if @data.empty?%>
    <h4>Data not available</h4> 
  <%else%>
    <div class="p1">
      <%= paginate @data %>
    </div>
    <div class="st_filter">
      <%= form_with url: gendersearch_path do |f| %>
        <%= f.label :gender %>      
        <%= select_tag("gender", options_for_select(gender_list,params[:per_page].to_i),
        {:name => "gender",:include_blank => 'Select Gender',:onchange=>"getlistbygender(this);"} ) %>
      <% end %>
    </div>
    <div class="js_gender">
    </div>
    <div class="st_index">
      <div class="box-body">
        <table id="datatbl",class="table table-hover">
          <thead>
            <tr>
              <th>Dimension </th>
              <th>British Columbia </th>
              <th>HA Total </th>
              <th>HA1 Interior </th>
              <th>HA2 Fraser </th>
              <th>Vancouver Coastal </th>
              <th>HA4 Vancouver Island </th>
              <th>HA5 Northern </th>
            </tr>
          </thead>
          <tbody>
            <%  @data.each do |data| %>
              <tr>
                <td><%= data.dimension %></td>
                <td><%= data.british_columbia %></td>
                <td><%= data.ha_total %></td>
                <td><%= data.ha1_interior %></td>
                <td><%= data.ha2_fraser %></td>
                <td><%= data.ha3_vancouver_coastal %></td>
                <td><%= data.ha4_vancouver_island %></td>
                <td><%= data.ha5_northern %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <%end%>
</div>

  